# Generated by Django 4.2.2 on 2023-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('FT', 'Future'), ('NW', 'Now'), ('FN', 'Finished')], default='FT', max_length=2),
        ),
    ]
